### ISSUE TITLE
error while logging out

### ISSUE THREAD

**Issue by swarajbachu** [Aperturs/aperturs-github#6]
<img width="1072" alt="Screenshot 2023-05-27 at 10 56 12 AM" src="https://github.com/Aperturs/aperturs-github/assets/97094800/58686588-d65e-45a3-90ce-2c3dd1b514b6">

try logging out twice, you will be able to find this error

**Comment by shivanshu814** [comment]
you can use any auth that will be easy for you i think
clerk auth which gives you signin signout button as well and profile also.

**Comment by swarajbachu** [comment]
Thank you for the suggestion! Actually we are building the auth of this project for temporary purpose, which is for the Appwrite Hackathon, on the longrun we are planning of using clerk auth itself

**Comment by shivanshu814** [comment]
yes use clerk that is best
can i participate with you in this project ??

**Comment by swarajbachu** [comment]
Absolutely, 

Certainly, you are more than welcome to participate in this project with us. 

Our goal is to make the issues more understandable and easy to work on, so that you can continue making progress on them. 
If you enjoy the work and find it fulfilling, I would be delighted to collaborate with you further. 
Your contribution and expertise would be highly valued. Thank you for your interest, and I look forward to working together!

**Comment by shivanshu814** [comment]
Just Have a Meet to discuss about the project I think this is your startup also.
we can connect on linkedin.

**Comment by swarajbachu** [comment]
#14
